
# Handling Reading
safe: true
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Conversion
markdown: kramdown
highlights: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

timezone: Asia/Shanghai

# Outputting
permalink: /article/:year/:month/:title.html
paginate: 4
paginate_path: /page:num

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
  enable_coderay: true
  syntax_highlighter: coderay

JB:
  IMAGE_PATH: /images

# Default custom settings
domain: blog.kedyy.com
cdn_url:
title: KEDYY
description: 追求简单高效
author: KEDYY
email: webmaster@KEDYY.COM
theme_color: 00897B

config:
  js_dir: /js
  img_dir: /images
  css_dir: /css

gems: [jekyll-paginate]