permalink: /blog/:year/:month/:title.html 

# Handling Reading
safe: true
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Conversion
markdown: kramdown
highlights: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

timezone: Asia/Shanghai
auto: false 
theme_color: 00897B

# Outputting
permalink: date
paginate: 4
paginate_path: /page:num

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
  enable_coderay: true
  syntax_highlighter: coderay

JB :
  IMAGE_PATH : /images

# presonal config
domain: blog.kedyy.com
url: https://blog.kedyy.com
cdn_url: 
title: KEDYY
description: 简单 高效
author: Yifei0727
email: Yifei0727+github@gmail.com
github: KEDYY

config:
  js_dir: /js
  img_dir: /img
  css_dir: /css

gems: [jekyll-paginate]  

theme: jekyll-theme-minimal