permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlights: pygments
url: blog.kedyy.com
cdn_url: 7u2t01.com1.z0.glb.clouddn.com
lsi: false
safe: true
timezone: Asia/Shanghai
auto: false 
theme_color: 00897B

  
paginate: 4
paginate_path: "/page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: enable_coderay

JB :
  IMAGE_PATH : http://blog.kedyy.com/images

# presonal config
domain: http://blog.kedyy.com
title: KEDYY
description: 简单 高效
author: Yifei0727
email: Yifei0727+github@gmail.com
github: KEDYY

config:
  js_dir:
  img_dir:
  css_dir:

gems: [jekyll-paginate]  
